[[constraint]]
  name = "github.com/deislabs/cnab-go"
  source = "github.com/radu-matei/cnab-go"
  branch = "add-duffle-types"

 [[constraint]]
   name = "github.com/deislabs/oras"
   branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/pivotal/image-relocation"
  branch = "master"

[[override]]
  name = "github.com/docker/docker"
  revision = "8a43b7bb99cd1eedc3aca61fbc3ccfba6b75c209"

[prune]
  go-tests = true
  unused-packages = true
